version: "3.7"

services:
  proxy-server:
    image: jwilder/nginx-proxy:alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - ~/certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./proxy.conf:/etc/nginx/proxy.conf
      - html:/usr/share/nginx/html
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-network
    deploy:
      mode: global

volumes:
  html:

networks:
  proxy-network:
    name: "${NETWORK}"
    driver: overlay
