version: "3.7"

services:
  server:
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      mode: global

networks:
  proxy:
    driver: overlay
