version: "3.7"

services:
  server:
    image: jwilder/nginx-proxy:alpine
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d:ro
      - ./conf.d:/etc/nginx/conf.d
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

volumes:
  html:

networks:
  proxy:
    name: "${NETWORK}"
